spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3307/travel-accommodation?useSSL=false
    username: root
    password: 1234
    hikari:
      pool-name: main-HikariPool
      maximum-pool-size: 10
      connection-timeout: 20000
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        ejb:
          use_class_enhancer: false
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
  transaction:
    default-timeout: 5
    rollback-on-commit-failure: true
logging:
  level:
    org.hibernate.sql: debug